// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: pkg/plugin/proto/plugin.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request/Response messages for metadata
type MetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataRequest) Reset() {
	*x = MetadataRequest{}
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataRequest) ProtoMessage() {}

func (x *MetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataRequest.ProtoReflect.Descriptor instead.
func (*MetadataRequest) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_proto_plugin_proto_rawDescGZIP(), []int{0}
}

type MetadataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Author        string                 `protobuf:"bytes,4,opt,name=author,proto3" json:"author,omitempty"`
	Tags          []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataResponse) Reset() {
	*x = MetadataResponse{}
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataResponse) ProtoMessage() {}

func (x *MetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataResponse.ProtoReflect.Descriptor instead.
func (*MetadataResponse) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_proto_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *MetadataResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MetadataResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *MetadataResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MetadataResponse) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *MetadataResponse) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

// Request/Response messages for actions
type ActionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionsRequest) Reset() {
	*x = ActionsRequest{}
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionsRequest) ProtoMessage() {}

func (x *ActionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionsRequest.ProtoReflect.Descriptor instead.
func (*ActionsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_proto_plugin_proto_rawDescGZIP(), []int{2}
}

type ActionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actions       []*Action              `protobuf:"bytes,1,rep,name=actions,proto3" json:"actions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionsResponse) Reset() {
	*x = ActionsResponse{}
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionsResponse) ProtoMessage() {}

func (x *ActionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionsResponse.ProtoReflect.Descriptor instead.
func (*ActionsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_proto_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *ActionsResponse) GetActions() []*Action {
	if x != nil {
		return x.Actions
	}
	return nil
}

type Action struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Inputs        map[string]*InputSpec  `protobuf:"bytes,3,rep,name=inputs,proto3" json:"inputs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Outputs       map[string]*OutputSpec `protobuf:"bytes,4,rep,name=outputs,proto3" json:"outputs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Action) Reset() {
	*x = Action{}
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Action) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action) ProtoMessage() {}

func (x *Action) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Action.ProtoReflect.Descriptor instead.
func (*Action) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_proto_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *Action) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Action) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Action) GetInputs() map[string]*InputSpec {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *Action) GetOutputs() map[string]*OutputSpec {
	if x != nil {
		return x.Outputs
	}
	return nil
}

type InputSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Required      bool                   `protobuf:"varint,3,opt,name=required,proto3" json:"required,omitempty"`
	DefaultValue  *Value                 `protobuf:"bytes,4,opt,name=default_value,json=defaultValue,proto3" json:"default_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InputSpec) Reset() {
	*x = InputSpec{}
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputSpec) ProtoMessage() {}

func (x *InputSpec) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputSpec.ProtoReflect.Descriptor instead.
func (*InputSpec) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_proto_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *InputSpec) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *InputSpec) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *InputSpec) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *InputSpec) GetDefaultValue() *Value {
	if x != nil {
		return x.DefaultValue
	}
	return nil
}

type OutputSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutputSpec) Reset() {
	*x = OutputSpec{}
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutputSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutputSpec) ProtoMessage() {}

func (x *OutputSpec) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutputSpec.ProtoReflect.Descriptor instead.
func (*OutputSpec) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_proto_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *OutputSpec) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *OutputSpec) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// Request/Response messages for validation
type ValidateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	Params        map[string]*Value      `protobuf:"bytes,2,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateRequest) Reset() {
	*x = ValidateRequest{}
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateRequest) ProtoMessage() {}

func (x *ValidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateRequest.ProtoReflect.Descriptor instead.
func (*ValidateRequest) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_proto_plugin_proto_rawDescGZIP(), []int{7}
}

func (x *ValidateRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ValidateRequest) GetParams() map[string]*Value {
	if x != nil {
		return x.Params
	}
	return nil
}

type ValidateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Errors        []string               `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateResponse) Reset() {
	*x = ValidateResponse{}
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateResponse) ProtoMessage() {}

func (x *ValidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateResponse.ProtoReflect.Descriptor instead.
func (*ValidateResponse) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_proto_plugin_proto_rawDescGZIP(), []int{8}
}

func (x *ValidateResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateResponse) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

// Request/Response messages for execution
type ExecuteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	Params        map[string]*Value      `protobuf:"bytes,2,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Context       *ExecuteContext        `protobuf:"bytes,3,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_proto_plugin_proto_rawDescGZIP(), []int{9}
}

func (x *ExecuteRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ExecuteRequest) GetParams() map[string]*Value {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *ExecuteRequest) GetContext() *ExecuteContext {
	if x != nil {
		return x.Context
	}
	return nil
}

type ExecuteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Outputs       map[string]*Value      `protobuf:"bytes,2,rep,name=outputs,proto3" json:"outputs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	Metrics       *ExecuteMetrics        `protobuf:"bytes,4,opt,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_proto_plugin_proto_rawDescGZIP(), []int{10}
}

func (x *ExecuteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ExecuteResponse) GetOutputs() map[string]*Value {
	if x != nil {
		return x.Outputs
	}
	return nil
}

func (x *ExecuteResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ExecuteResponse) GetMetrics() *ExecuteMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type ExecuteContext struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId     string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	StepId         string                 `protobuf:"bytes,2,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	TimeoutSeconds int64                  `protobuf:"varint,3,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	Environment    map[string]string      `protobuf:"bytes,4,rep,name=environment,proto3" json:"environment,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExecuteContext) Reset() {
	*x = ExecuteContext{}
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteContext) ProtoMessage() {}

func (x *ExecuteContext) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteContext.ProtoReflect.Descriptor instead.
func (*ExecuteContext) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_proto_plugin_proto_rawDescGZIP(), []int{11}
}

func (x *ExecuteContext) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *ExecuteContext) GetStepId() string {
	if x != nil {
		return x.StepId
	}
	return ""
}

func (x *ExecuteContext) GetTimeoutSeconds() int64 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *ExecuteContext) GetEnvironment() map[string]string {
	if x != nil {
		return x.Environment
	}
	return nil
}

type ExecuteMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DurationMs    int64                  `protobuf:"varint,1,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	MemoryBytes   int64                  `protobuf:"varint,2,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteMetrics) Reset() {
	*x = ExecuteMetrics{}
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteMetrics) ProtoMessage() {}

func (x *ExecuteMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteMetrics.ProtoReflect.Descriptor instead.
func (*ExecuteMetrics) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_proto_plugin_proto_rawDescGZIP(), []int{12}
}

func (x *ExecuteMetrics) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *ExecuteMetrics) GetMemoryBytes() int64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *ExecuteMetrics) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// Health check messages
type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_proto_plugin_proto_rawDescGZIP(), []int{13}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_proto_plugin_proto_rawDescGZIP(), []int{14}
}

func (x *HealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// Value represents any JSON-like value
type Value struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*Value_StringValue
	//	*Value_NumberValue
	//	*Value_BoolValue
	//	*Value_ArrayValue
	//	*Value_ObjectValue
	//	*Value_NullValue
	Kind          isValue_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Value) Reset() {
	*x = Value{}
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_proto_plugin_proto_rawDescGZIP(), []int{15}
}

func (x *Value) GetKind() isValue_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Value) GetStringValue() string {
	if x != nil {
		if x, ok := x.Kind.(*Value_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *Value) GetNumberValue() float64 {
	if x != nil {
		if x, ok := x.Kind.(*Value_NumberValue); ok {
			return x.NumberValue
		}
	}
	return 0
}

func (x *Value) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Kind.(*Value_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *Value) GetArrayValue() *ValueArray {
	if x != nil {
		if x, ok := x.Kind.(*Value_ArrayValue); ok {
			return x.ArrayValue
		}
	}
	return nil
}

func (x *Value) GetObjectValue() *ValueObject {
	if x != nil {
		if x, ok := x.Kind.(*Value_ObjectValue); ok {
			return x.ObjectValue
		}
	}
	return nil
}

func (x *Value) GetNullValue() structpb.NullValue {
	if x != nil {
		if x, ok := x.Kind.(*Value_NullValue); ok {
			return x.NullValue
		}
	}
	return structpb.NullValue(0)
}

type isValue_Kind interface {
	isValue_Kind()
}

type Value_StringValue struct {
	StringValue string `protobuf:"bytes,1,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type Value_NumberValue struct {
	NumberValue float64 `protobuf:"fixed64,2,opt,name=number_value,json=numberValue,proto3,oneof"`
}

type Value_BoolValue struct {
	BoolValue bool `protobuf:"varint,3,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type Value_ArrayValue struct {
	ArrayValue *ValueArray `protobuf:"bytes,4,opt,name=array_value,json=arrayValue,proto3,oneof"`
}

type Value_ObjectValue struct {
	ObjectValue *ValueObject `protobuf:"bytes,5,opt,name=object_value,json=objectValue,proto3,oneof"`
}

type Value_NullValue struct {
	NullValue structpb.NullValue `protobuf:"varint,6,opt,name=null_value,json=nullValue,proto3,enum=google.protobuf.NullValue,oneof"`
}

func (*Value_StringValue) isValue_Kind() {}

func (*Value_NumberValue) isValue_Kind() {}

func (*Value_BoolValue) isValue_Kind() {}

func (*Value_ArrayValue) isValue_Kind() {}

func (*Value_ObjectValue) isValue_Kind() {}

func (*Value_NullValue) isValue_Kind() {}

type ValueArray struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []*Value               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValueArray) Reset() {
	*x = ValueArray{}
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValueArray) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValueArray) ProtoMessage() {}

func (x *ValueArray) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValueArray.ProtoReflect.Descriptor instead.
func (*ValueArray) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_proto_plugin_proto_rawDescGZIP(), []int{16}
}

func (x *ValueArray) GetValues() []*Value {
	if x != nil {
		return x.Values
	}
	return nil
}

type ValueObject struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fields        map[string]*Value      `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValueObject) Reset() {
	*x = ValueObject{}
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValueObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValueObject) ProtoMessage() {}

func (x *ValueObject) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_proto_plugin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValueObject.ProtoReflect.Descriptor instead.
func (*ValueObject) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_proto_plugin_proto_rawDescGZIP(), []int{17}
}

func (x *ValueObject) GetFields() map[string]*Value {
	if x != nil {
		return x.Fields
	}
	return nil
}

var File_pkg_plugin_proto_plugin_proto protoreflect.FileDescriptor

const file_pkg_plugin_proto_plugin_proto_rawDesc = "" +
	"\n" +
	"\x1dpkg/plugin/proto/plugin.proto\x12\x11corynth.plugin.v1\x1a\x1cgoogle/protobuf/struct.proto\"\x11\n" +
	"\x0fMetadataRequest\"\x8e\x01\n" +
	"\x10MetadataResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06author\x18\x04 \x01(\tR\x06author\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\"\x10\n" +
	"\x0eActionsRequest\"F\n" +
	"\x0fActionsResponse\x123\n" +
	"\aactions\x18\x01 \x03(\v2\x19.corynth.plugin.v1.ActionR\aactions\"\xf3\x02\n" +
	"\x06Action\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12=\n" +
	"\x06inputs\x18\x03 \x03(\v2%.corynth.plugin.v1.Action.InputsEntryR\x06inputs\x12@\n" +
	"\aoutputs\x18\x04 \x03(\v2&.corynth.plugin.v1.Action.OutputsEntryR\aoutputs\x1aW\n" +
	"\vInputsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x122\n" +
	"\x05value\x18\x02 \x01(\v2\x1c.corynth.plugin.v1.InputSpecR\x05value:\x028\x01\x1aY\n" +
	"\fOutputsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x123\n" +
	"\x05value\x18\x02 \x01(\v2\x1d.corynth.plugin.v1.OutputSpecR\x05value:\x028\x01\"\x9c\x01\n" +
	"\tInputSpec\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1a\n" +
	"\brequired\x18\x03 \x01(\bR\brequired\x12=\n" +
	"\rdefault_value\x18\x04 \x01(\v2\x18.corynth.plugin.v1.ValueR\fdefaultValue\"B\n" +
	"\n" +
	"OutputSpec\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"\xc6\x01\n" +
	"\x0fValidateRequest\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12F\n" +
	"\x06params\x18\x02 \x03(\v2..corynth.plugin.v1.ValidateRequest.ParamsEntryR\x06params\x1aS\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12.\n" +
	"\x05value\x18\x02 \x01(\v2\x18.corynth.plugin.v1.ValueR\x05value:\x028\x01\"@\n" +
	"\x10ValidateResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x16\n" +
	"\x06errors\x18\x02 \x03(\tR\x06errors\"\x81\x02\n" +
	"\x0eExecuteRequest\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12E\n" +
	"\x06params\x18\x02 \x03(\v2-.corynth.plugin.v1.ExecuteRequest.ParamsEntryR\x06params\x12;\n" +
	"\acontext\x18\x03 \x01(\v2!.corynth.plugin.v1.ExecuteContextR\acontext\x1aS\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12.\n" +
	"\x05value\x18\x02 \x01(\v2\x18.corynth.plugin.v1.ValueR\x05value:\x028\x01\"\x9f\x02\n" +
	"\x0fExecuteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12I\n" +
	"\aoutputs\x18\x02 \x03(\v2/.corynth.plugin.v1.ExecuteResponse.OutputsEntryR\aoutputs\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12;\n" +
	"\ametrics\x18\x04 \x01(\v2!.corynth.plugin.v1.ExecuteMetricsR\ametrics\x1aT\n" +
	"\fOutputsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12.\n" +
	"\x05value\x18\x02 \x01(\v2\x18.corynth.plugin.v1.ValueR\x05value:\x028\x01\"\x89\x02\n" +
	"\x0eExecuteContext\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\x12\x17\n" +
	"\astep_id\x18\x02 \x01(\tR\x06stepId\x12'\n" +
	"\x0ftimeout_seconds\x18\x03 \x01(\x03R\x0etimeoutSeconds\x12T\n" +
	"\venvironment\x18\x04 \x03(\v22.corynth.plugin.v1.ExecuteContext.EnvironmentEntryR\venvironment\x1a>\n" +
	"\x10EnvironmentEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"l\n" +
	"\x0eExecuteMetrics\x12\x1f\n" +
	"\vduration_ms\x18\x01 \x01(\x03R\n" +
	"durationMs\x12!\n" +
	"\fmemory_bytes\x18\x02 \x01(\x03R\vmemoryBytes\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"\x0f\n" +
	"\rHealthRequest\"B\n" +
	"\x0eHealthResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"\xbe\x02\n" +
	"\x05Value\x12#\n" +
	"\fstring_value\x18\x01 \x01(\tH\x00R\vstringValue\x12#\n" +
	"\fnumber_value\x18\x02 \x01(\x01H\x00R\vnumberValue\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x03 \x01(\bH\x00R\tboolValue\x12@\n" +
	"\varray_value\x18\x04 \x01(\v2\x1d.corynth.plugin.v1.ValueArrayH\x00R\n" +
	"arrayValue\x12C\n" +
	"\fobject_value\x18\x05 \x01(\v2\x1e.corynth.plugin.v1.ValueObjectH\x00R\vobjectValue\x12;\n" +
	"\n" +
	"null_value\x18\x06 \x01(\x0e2\x1a.google.protobuf.NullValueH\x00R\tnullValueB\x06\n" +
	"\x04kind\">\n" +
	"\n" +
	"ValueArray\x120\n" +
	"\x06values\x18\x01 \x03(\v2\x18.corynth.plugin.v1.ValueR\x06values\"\xa6\x01\n" +
	"\vValueObject\x12B\n" +
	"\x06fields\x18\x01 \x03(\v2*.corynth.plugin.v1.ValueObject.FieldsEntryR\x06fields\x1aS\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12.\n" +
	"\x05value\x18\x02 \x01(\v2\x18.corynth.plugin.v1.ValueR\x05value:\x028\x012\xb8\x03\n" +
	"\rPluginService\x12V\n" +
	"\vGetMetadata\x12\".corynth.plugin.v1.MetadataRequest\x1a#.corynth.plugin.v1.MetadataResponse\x12S\n" +
	"\n" +
	"GetActions\x12!.corynth.plugin.v1.ActionsRequest\x1a\".corynth.plugin.v1.ActionsResponse\x12Y\n" +
	"\x0eValidateParams\x12\".corynth.plugin.v1.ValidateRequest\x1a#.corynth.plugin.v1.ValidateResponse\x12P\n" +
	"\aExecute\x12!.corynth.plugin.v1.ExecuteRequest\x1a\".corynth.plugin.v1.ExecuteResponse\x12M\n" +
	"\x06Health\x12 .corynth.plugin.v1.HealthRequest\x1a!.corynth.plugin.v1.HealthResponseB-Z+github.com/corynth/corynth/pkg/plugin/protob\x06proto3"

var (
	file_pkg_plugin_proto_plugin_proto_rawDescOnce sync.Once
	file_pkg_plugin_proto_plugin_proto_rawDescData []byte
)

func file_pkg_plugin_proto_plugin_proto_rawDescGZIP() []byte {
	file_pkg_plugin_proto_plugin_proto_rawDescOnce.Do(func() {
		file_pkg_plugin_proto_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_plugin_proto_plugin_proto_rawDesc), len(file_pkg_plugin_proto_plugin_proto_rawDesc)))
	})
	return file_pkg_plugin_proto_plugin_proto_rawDescData
}

var file_pkg_plugin_proto_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_pkg_plugin_proto_plugin_proto_goTypes = []any{
	(*MetadataRequest)(nil),  // 0: corynth.plugin.v1.MetadataRequest
	(*MetadataResponse)(nil), // 1: corynth.plugin.v1.MetadataResponse
	(*ActionsRequest)(nil),   // 2: corynth.plugin.v1.ActionsRequest
	(*ActionsResponse)(nil),  // 3: corynth.plugin.v1.ActionsResponse
	(*Action)(nil),           // 4: corynth.plugin.v1.Action
	(*InputSpec)(nil),        // 5: corynth.plugin.v1.InputSpec
	(*OutputSpec)(nil),       // 6: corynth.plugin.v1.OutputSpec
	(*ValidateRequest)(nil),  // 7: corynth.plugin.v1.ValidateRequest
	(*ValidateResponse)(nil), // 8: corynth.plugin.v1.ValidateResponse
	(*ExecuteRequest)(nil),   // 9: corynth.plugin.v1.ExecuteRequest
	(*ExecuteResponse)(nil),  // 10: corynth.plugin.v1.ExecuteResponse
	(*ExecuteContext)(nil),   // 11: corynth.plugin.v1.ExecuteContext
	(*ExecuteMetrics)(nil),   // 12: corynth.plugin.v1.ExecuteMetrics
	(*HealthRequest)(nil),    // 13: corynth.plugin.v1.HealthRequest
	(*HealthResponse)(nil),   // 14: corynth.plugin.v1.HealthResponse
	(*Value)(nil),            // 15: corynth.plugin.v1.Value
	(*ValueArray)(nil),       // 16: corynth.plugin.v1.ValueArray
	(*ValueObject)(nil),      // 17: corynth.plugin.v1.ValueObject
	nil,                      // 18: corynth.plugin.v1.Action.InputsEntry
	nil,                      // 19: corynth.plugin.v1.Action.OutputsEntry
	nil,                      // 20: corynth.plugin.v1.ValidateRequest.ParamsEntry
	nil,                      // 21: corynth.plugin.v1.ExecuteRequest.ParamsEntry
	nil,                      // 22: corynth.plugin.v1.ExecuteResponse.OutputsEntry
	nil,                      // 23: corynth.plugin.v1.ExecuteContext.EnvironmentEntry
	nil,                      // 24: corynth.plugin.v1.ValueObject.FieldsEntry
	(structpb.NullValue)(0),  // 25: google.protobuf.NullValue
}
var file_pkg_plugin_proto_plugin_proto_depIdxs = []int32{
	4,  // 0: corynth.plugin.v1.ActionsResponse.actions:type_name -> corynth.plugin.v1.Action
	18, // 1: corynth.plugin.v1.Action.inputs:type_name -> corynth.plugin.v1.Action.InputsEntry
	19, // 2: corynth.plugin.v1.Action.outputs:type_name -> corynth.plugin.v1.Action.OutputsEntry
	15, // 3: corynth.plugin.v1.InputSpec.default_value:type_name -> corynth.plugin.v1.Value
	20, // 4: corynth.plugin.v1.ValidateRequest.params:type_name -> corynth.plugin.v1.ValidateRequest.ParamsEntry
	21, // 5: corynth.plugin.v1.ExecuteRequest.params:type_name -> corynth.plugin.v1.ExecuteRequest.ParamsEntry
	11, // 6: corynth.plugin.v1.ExecuteRequest.context:type_name -> corynth.plugin.v1.ExecuteContext
	22, // 7: corynth.plugin.v1.ExecuteResponse.outputs:type_name -> corynth.plugin.v1.ExecuteResponse.OutputsEntry
	12, // 8: corynth.plugin.v1.ExecuteResponse.metrics:type_name -> corynth.plugin.v1.ExecuteMetrics
	23, // 9: corynth.plugin.v1.ExecuteContext.environment:type_name -> corynth.plugin.v1.ExecuteContext.EnvironmentEntry
	16, // 10: corynth.plugin.v1.Value.array_value:type_name -> corynth.plugin.v1.ValueArray
	17, // 11: corynth.plugin.v1.Value.object_value:type_name -> corynth.plugin.v1.ValueObject
	25, // 12: corynth.plugin.v1.Value.null_value:type_name -> google.protobuf.NullValue
	15, // 13: corynth.plugin.v1.ValueArray.values:type_name -> corynth.plugin.v1.Value
	24, // 14: corynth.plugin.v1.ValueObject.fields:type_name -> corynth.plugin.v1.ValueObject.FieldsEntry
	5,  // 15: corynth.plugin.v1.Action.InputsEntry.value:type_name -> corynth.plugin.v1.InputSpec
	6,  // 16: corynth.plugin.v1.Action.OutputsEntry.value:type_name -> corynth.plugin.v1.OutputSpec
	15, // 17: corynth.plugin.v1.ValidateRequest.ParamsEntry.value:type_name -> corynth.plugin.v1.Value
	15, // 18: corynth.plugin.v1.ExecuteRequest.ParamsEntry.value:type_name -> corynth.plugin.v1.Value
	15, // 19: corynth.plugin.v1.ExecuteResponse.OutputsEntry.value:type_name -> corynth.plugin.v1.Value
	15, // 20: corynth.plugin.v1.ValueObject.FieldsEntry.value:type_name -> corynth.plugin.v1.Value
	0,  // 21: corynth.plugin.v1.PluginService.GetMetadata:input_type -> corynth.plugin.v1.MetadataRequest
	2,  // 22: corynth.plugin.v1.PluginService.GetActions:input_type -> corynth.plugin.v1.ActionsRequest
	7,  // 23: corynth.plugin.v1.PluginService.ValidateParams:input_type -> corynth.plugin.v1.ValidateRequest
	9,  // 24: corynth.plugin.v1.PluginService.Execute:input_type -> corynth.plugin.v1.ExecuteRequest
	13, // 25: corynth.plugin.v1.PluginService.Health:input_type -> corynth.plugin.v1.HealthRequest
	1,  // 26: corynth.plugin.v1.PluginService.GetMetadata:output_type -> corynth.plugin.v1.MetadataResponse
	3,  // 27: corynth.plugin.v1.PluginService.GetActions:output_type -> corynth.plugin.v1.ActionsResponse
	8,  // 28: corynth.plugin.v1.PluginService.ValidateParams:output_type -> corynth.plugin.v1.ValidateResponse
	10, // 29: corynth.plugin.v1.PluginService.Execute:output_type -> corynth.plugin.v1.ExecuteResponse
	14, // 30: corynth.plugin.v1.PluginService.Health:output_type -> corynth.plugin.v1.HealthResponse
	26, // [26:31] is the sub-list for method output_type
	21, // [21:26] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_pkg_plugin_proto_plugin_proto_init() }
func file_pkg_plugin_proto_plugin_proto_init() {
	if File_pkg_plugin_proto_plugin_proto != nil {
		return
	}
	file_pkg_plugin_proto_plugin_proto_msgTypes[15].OneofWrappers = []any{
		(*Value_StringValue)(nil),
		(*Value_NumberValue)(nil),
		(*Value_BoolValue)(nil),
		(*Value_ArrayValue)(nil),
		(*Value_ObjectValue)(nil),
		(*Value_NullValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_plugin_proto_plugin_proto_rawDesc), len(file_pkg_plugin_proto_plugin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_plugin_proto_plugin_proto_goTypes,
		DependencyIndexes: file_pkg_plugin_proto_plugin_proto_depIdxs,
		MessageInfos:      file_pkg_plugin_proto_plugin_proto_msgTypes,
	}.Build()
	File_pkg_plugin_proto_plugin_proto = out.File
	file_pkg_plugin_proto_plugin_proto_goTypes = nil
	file_pkg_plugin_proto_plugin_proto_depIdxs = nil
}
